name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true

      - name: Copy test execution videos and screenshots
        run: |
          mkdir -p public/videos
          mkdir -p public/screenshots
          cp -r cypress/videos/* public/videos || echo "No videos to copy"
          cp -r cypress/screenshots/* public/screenshots || echo "No screenshots to copy"
