name: Cypress Tests

on: 
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in ${{ matrix.browsers }}
        run: >
          npx cypress run --browser ${{ matrix.browsers }}

      - name: List JSON report files
        run: ls -R cypress/results || echo "No results found"

      - name: Merge Mochawesome reports
        run: >
          npx mochawesome-merge cypress/results/*.json 
          > cypress/results/merged-${{ matrix.browsers }}.json

      - name: Generate Mochawesome HTML report (inline assets)
        run: >
          npx marge cypress/results/merged-${{ matrix.browsers }}.json 
          --reportDir cypress/results 
          -f "${{ matrix.browsers }}-report.html" 
          --inline

      - name: List generated HTML files
        run: ls -l cypress/results || echo "No HTML report generated"

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome Report - ${{ matrix.browsers }}
          path: cypress/results/${{ matrix.browsers }}-report.html
